// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6hkopA_4WoEBMcItfsHmfksBYKGL29vs',
    appId: '1:521138556513:web:850de1bbc894cbd725e420',
    messagingSenderId: '521138556513',
    projectId: 'smartcanteen-6764c',
    authDomain: 'smartcanteen-6764c.firebaseapp.com',
    storageBucket: 'smartcanteen-6764c.firebasestorage.app',
    measurementId: 'G-1XB69GQ01R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnzkNC4y3tF7poHUamFoXFsvjp13NMy4A',
    appId: '1:521138556513:android:206033a1757f7f4a25e420',
    messagingSenderId: '521138556513',
    projectId: 'smartcanteen-6764c',
    storageBucket: 'smartcanteen-6764c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKGWOX8PY9qCyE5_3vujFEbuvnXpcrxk',
    appId: '1:521138556513:ios:f95c8149b5f88dd625e420',
    messagingSenderId: '521138556513',
    projectId: 'smartcanteen-6764c',
    storageBucket: 'smartcanteen-6764c.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
